name: Shopping Cart Flow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Snap and K6
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install k6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Display Coverage Summary
        run: |
          echo "Coverage Summary:"
          cat ./coverage/lcov-report/index.html


